name: Rust and Perseus Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install cargo-hakari
      uses: baptiste0928/cargo-install@v1
      with:
        crate: perseus-cli
        version: "0.4.0-beta.11"
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run generation
      run: perseus build
